<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="head_unit">
  <xacro:property name="pi" value="3.14159265359" />

  <link name="head_unit">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <box size="0.1268 0.1525 0.0095" />
      </geometry>
      <material name="grey">
        <color rgba="0.5 0.5 0.5 1"/>
      </material>
    </visual>
  </link>
  
  <joint name="base_link_to_head_unit" type="fixed">
    <parent link="base_link" />
    <child link="head_unit" />
    <origin xyz="0 0 ${platform_h + 0.014}" rpy="0 0 0" /> <!-- fix height -->
  </joint>

  <link name="t-slot-rod">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
         <mesh filename="package://head_unit/urdf/meshes/t-slot-rod.stl" scale="1 1 0.168"/>
      </geometry>
      <material name="grey"/>
    </visual>
  </link>

  <joint name="head_unit_to_t-slot-rod" type="fixed">
    <parent link="head_unit" />
    <child link="t-slot-rod" />
    <origin xyz="0 0 ${0.2159/2}" rpy="0 0 0" />
  </joint>

  <xacro:macro name="t-slot-bracket" params="name xyz rpy">
    <link name="t-slot-bracket-${name}">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
           <mesh filename="package://head_unit/urdf/meshes/t-slot-bracket.stl" scale="1 1 1"/>
        </geometry>
        <material name="grey" />
      </visual>
    </link>

    <joint name="head_unit_to_t-slot-bracket-${name}" type="fixed">
      <parent link="head_unit" />
      <child link="t-slot-bracket-${name}" />
      <origin xyz="${xyz}" rpy="${rpy}" />
    </joint>
  </xacro:macro>

  <xacro:t-slot-bracket name="bottom-left" xyz="0 0.0191 0.004" rpy="${pi/2} 0 ${pi/2}" />
  <xacro:t-slot-bracket name="bottom-right" xyz="0 -0.0191 0.004" rpy="${pi/2} 0 -${pi/2}" />
  <xacro:t-slot-bracket name="top-left" xyz="0 0.0191 0.211" rpy="-${pi/2} 0 ${pi/2}" />
  <xacro:t-slot-bracket name="top-right" xyz="0 -0.0191 0.211" rpy="-${pi/2} 0 -${pi/2}" />

  <link name="kinect_mount">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <box size="0.0677 0.1120 0.0200" />
      </geometry>
      <material name="black" />
    </visual>
  </link>

  <joint name="head_unit_to_kinect_mount" type="fixed">
    <parent link="head_unit" />
    <child link="kinect_mount" />
    <origin xyz="-0.013 0 0.2215" rpy="0 0 0 " />
  </joint>

  <xacro:include filename="../../head_unit/urdf/kinect2.xacro" />
  <xacro:include filename="../../head_unit/urdf/project_tango.xacro" />
</robot>
