obstacle_range: 6.5
raytrace_range: 7.0
footprint: [[0.31, 0.31], [0.31, -0.31], [-0.31, -0.31], [-0.31, 0.31]]
#robot_radius: ir_of_robot
inflation_radius: 0.2

observation_sources: laser_scan_sensor point_cloud_sensor

laser_scan_sensor: {sensor_frame: camera_depth_frame, data_type: LaserScan, topic: kinect_scan, marking: true, clearing: true}

point_cloud_sensor: {sensor_frame: kinect2_ir_optical_frame, data_type: PointCloud, topic: kinect2/sd/points, marking: true, clearing: false}
